{
 "title": "Purebred Dogs of Zurich",
 "time": { "from": "1970-01-01T00:00:02.010Z", "to": "1970-01-01T00:00:02.011Z" },
 "templating": {
  "list": [
   {
    "name": "kreisdropdown",
    "label": "Kreis",
    "query": "SELECT DISTINCT description FROM Kreis"
   },
   {
    "name": "quartierdropdown",
    "label": "Quartier",
    "query": "SELECT DISTINCT description FROM quartier"
   },
   {
    "name": "breeddropdown",
    "label": "Breed",
    "query": "SELECT DISTINCT description FROM breed"
   }
  ]
 },
 "panels": [
  {
   "title": "Timeline of $breeddropdown ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Number of Dogs\", birthyear as time\nFROM dog\nINNER JOIN breed ON dog.breedid1 = breed.id\nWHERE breed.description = '$breeddropdown'\nGROUP BY birthyear\n"
    }
   ]
  },
  {
   "title": "Timeline of Breeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  breed.description as \"Breed\", COUNT(dog.id) as \"Number of \", birthyear as \"time\"\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id\r\nGROUP BY breed.description, \"time\"\r\nORDER BY \"time\" ASC\r\n"
    }
   ]
  },
  {
   "title": "Number of dogs by breed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT kreis.description as \"Kreis\", COUNT(kreis.id) as \"Number of Dogs\"\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id \r\nINNER JOIN dogowner ON dog.ownerid = dogowner.id\r\nINNER JOIN kreis ON dogowner.kreisid = kreis.id\r\nWHERE dog.breedstatusid = 1 AND breed.description = '$breeddropdown'\r\nGROUP BY kreis.description, kreis.id\r\nORDER BY COUNT(kreis.id) DESC\r\nLIMIT 1;\r\n\r\n"
    },
    {
     "rawSql": "SELECT quartier.description as \"Quartier\", COUNT(quartier.id) as \"Number of Dogs\"\nFROM dog\nINNER JOIN breed ON dog.breedid1 = breed.id \nINNER JOIN dogowner ON dog.ownerid = dogowner.id\nINNER JOIN quartier ON dogowner.quartierid = quartier.id\nWHERE dog.breedstatusid = 1 AND breed.description = '$breeddropdown'\nGROUP BY quartier.description, quartier.id\nORDER BY COUNT(quartier.id) DESC\nLIMIT 1;\n\n"
    }
   ]
  },
  {
   "title": "Dogs grouped by birthyear",
   "type": "timeseries",
   "description": "All dogs purebred or mixed are shown and when they where born",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Number of Dogs\", birthyear as time\nFROM dog\n\nGROUP BY birthyear\n"
    }
   ]
  },
  {
   "title": "Pie chart of top 15 Pure-bred Breeds",
   "type": "piechart",
   "description": "\n\nTop 15 most owned pure breed dog breeds in the City of Zuerich.\n\nplease remember that pure-bred does not equal well-bred - adopt or shop responsibly! and no your designer breed is not a breed and will never be well-bred it will always remain an overpriced mutt",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT breed.description, count(breedid1) as breeds\r\nFROM dog\r\ninner join breed on dog.breedid1 = breed.id WHERE dog.breedstatusid = 1\r\nGROUP by dog.breedid1, breed.description\r\nORDER By breeds DESC"
    }
   ]
  },
  {
   "title": "Top 15 Pure-bred Breeds by Quartier",
   "type": "gauge",
   "description": "\n\nTop 15 most owned pure breed dog breeds in the City of Zuerich.\n\nplease remember that pure-bred does not equal well-bred - adopt or shop responsibly! and no your designer breed is not a breed and will never be well-bred it will always remain an overpriced mutt",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT breed.description, count(breedid1) as breeds\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id \r\nINNER JOIN dogowner ON dog.ownerid = dogowner.id\r\nINNER JOIN quartier ON dogowner.quartierid = quartier.id\r\nWHERE dog.breedstatusid = 1 AND quartier.description = '$quartierdropdown'\r\nGROUP BY dog.breedid1, breed.description\r\nORDER BY breeds DESC"
    }
   ]
  },
  {
   "title": "Top 15 Pure-bred Breeds by Kreis",
   "type": "gauge",
   "description": "\n\nTop 15 most owned pure breed dog breeds in the City of Zuerich.\n\nplease remember that pure-bred does not equal well-bred - adopt or shop responsibly! and no your designer breed is not a breed and will never be well-bred it will always remain an overpriced mutt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT breed.description, count(breedid1) as breeds\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id \r\nINNER JOIN dogowner ON dog.ownerid = dogowner.id\r\nINNER JOIN kreis ON dogowner.kreisid = kreis.id\r\nWHERE dog.breedstatusid = 1 AND kreis.description = '$kreisdropdown'\r\nGROUP BY dog.breedid1, breed.description\r\nORDER BY breeds DESC"
    }
   ]
  },
  {
   "title": "Top 10 most rare Pure-bred Breeds by Kreis",
   "type": "bargauge",
   "description": "\n\nTop 15 most owned pure breed dog breeds in the City of Zuerich.\n\nplease remember that pure-bred does not equal well-bred - adopt or shop responsibly! and no your designer breed is not a breed and will never be well-bred it will always remain an overpriced mutt",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT breed.description, count(breedid1) as breeds\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id \r\nINNER JOIN dogowner ON dog.ownerid = dogowner.id\r\nINNER JOIN kreis ON dogowner.kreisid = kreis.id\r\nWHERE dog.breedstatusid = 1 AND kreis.description = '$kreisdropdown'\r\nGROUP BY dog.breedid1, breed.description\r\nORDER BY breeds ASC"
    }
   ]
  },
  {
   "title": "Top 10 most rare Dog breeds by Quartier",
   "type": "bargauge",
   "description": "\n\nTop 15 most owned pure breed dog breeds in the City of Zuerich.\n\nplease remember that pure-bred does not equal well-bred - adopt or shop responsibly! and no your designer breed is not a breed and will never be well-bred it will always remain an overpriced mutt",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT breed.description, count(breedid1) as breeds\r\nFROM dog\r\nINNER JOIN breed ON dog.breedid1 = breed.id \r\nINNER JOIN dogowner ON dog.ownerid = dogowner.id\r\nINNER JOIN quartier ON dogowner.quartierid = quartier.id\r\nWHERE dog.breedstatusid = 1 AND quartier.description = '$quartierdropdown'\r\nGROUP BY dog.breedid1, breed.description\r\nORDER BY breeds ASC"
    }
   ]
  }
 ]
}